export const courses = [
  {
    id: 1,
    name: 'Italian Pasta Masterclass',
    instructor: 'Chef Marco Rossi',
    duration: '3 hours',
    price: 850,
    soldOut: false,
    emoji: '🍝',
  },
  {
    id: 2,
    name: 'Sushi & Sashimi Basics',
    instructor: 'Chef Yuki Tanaka',
    duration: '4 hours',
    price: 1200,
    soldOut: false,
    emoji: '🍣',
  },
  {
    id: 3,
    name: 'French Pastry Essentials',
    instructor: 'Chef Claire Dubois',
    duration: '5 hours',
    price: 1450,
    soldOut: true,
    emoji: '🥐',
  },
  {
    id: 4,
    name: 'Middle Eastern Feasts',
    instructor: 'Chef Omar Hassan',
    duration: '3.5 hours',
    price: 950,
    soldOut: false,
    emoji: '🍲',
  },
  {
    id: 5,
    name: 'South African Braai',
    instructor: 'Chef Siya Ndlovu',
    duration: '4 hours',
    price: 700,
    soldOut: false,
    emoji: '🥩',
  },
  {
    id: 6,
    name: 'Thai Street Food',
    instructor: 'Chef Niran Jit',
    duration: '3 hours',
    price: 800,
    soldOut: false,
    emoji: '🍜',
  },
  {
    id: 7,
    name: 'Artisan Bread Baking',
    instructor: 'Chef Baker Tom',
    duration: '6 hours',
    price: 1100,
    soldOut: true,
    emoji: '🍞',
  },
  {
    id: 8,
    name: 'Modern Dessert Plating',
    instructor: 'Chef Lisa Chen',
    duration: '3 hours',
    price: 1300,
    soldOut: false,
    emoji: '🍰',
  },
]

export const TAX_RATE = 0.15
